version: 2
formats:
  - pdf
  - epub
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
  system_packages: true
