language: python
sudo: false
cache: pip
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
before_install:
    - pip install tox
# command to run tests
script:
    - tox
